### ISSUE TITLE
Sending simple SMS is not clear

### ISSUE THREAD

**Issue by eduolalo** [infobip/infobip-api-go-client#3]
I tried to follow your documentation, but is not clear how to send a single SMS

In your Readme there is an object called "message" but it is never used in the methods to send it
how should I use that message object??
<img width="875" alt="Captura de Pantalla 2022-08-23 a la(s) 7 09 04 p m" src="https://user-images.githubusercontent.com/1189660/186295612-0e05d12c-66ba-42c8-b190-20de24cdb36c.png">

**Comment by juliacodez** [comment]
Hey @kalmecak, thanks for raising this issue on our generated Go client! It does look like a part of the code snippet is missing. 

While we sort that out, why don't you give our new hand-written SDK a try? 
https://github.com/infobip-community/infobip-api-go-sdk 

You can find instructions in the readme, and ready-to-use sample code under examples—just fill in your API key, base URL, and destination number.
https://github.com/infobip-community/infobip-api-go-sdk/blob/main/examples/sms_live_test.go

**Comment by kalmecak** [comment]
@juliacodez  Nice tip, I just added to mi protect and it worked very well!

**Comment by ib-plivaja** [comment]
Hi @eduolalo! Sorry for the late response.
I'm attaching code snippet for sending SMS message.

![image](https://user-images.githubusercontent.com/122616713/212669773-5a3e3388-4d27-45cf-bc11-2d2bf4b3548d.png)

I hope it will help you to use our library. Thank you for reaching us!

Best regards,
Petra
